version: "3.3"
volumes:
  bitcoin-data:
  metashrew-data:
  secondary-data:
services:
  bitcoind:
    image: bitcoind:alkanes
    build:
      dockerfile: Dockerfile
      context: ./docker/bitcoind
    volumes:
      - bitcoin-data:/root/.bitcoin
    command:
      ["-txindex", "-regtest=1", "-printtoconsole", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=bitcoinrpc", "-rpcpassword=bitcoinrpc"]
    restart: unless-stopped
  metashrew:
    build:
      dockerfile: Dockerfile
      context: ./docker/metashrew
    image: rockshrew:alkanes
    volumes:
      - metashrew-data:/data
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18443
      AUTH: bitcoinrpc:bitcoinrpc
      DB_PATH: /data
      LOG_FILTERS: none,rockshrew=debug
      HOST: 0.0.0.0
      PORT: 8080
    restart: unless-stopped
  memshrew:
    build:
      dockerfile: Dockerfile
      context: ./docker/memshrew
    image: memshrew:alkanes
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18443
      P2P_ADDR: bitcoind:18444
      AUTH: bitcoinrpc:bitcoinrpc
      LOG_FILTERS: none,memshrew=debug
      HOST: 0.0.0.0
      PORT: 8080
    restart: unless-stopped
  jsonrpc:
    build:
      dockerfile: Dockerfile
      context: ./jsonrpc
    image: jsonrpc:alkanes
    environment:
      HOST: 0.0.0.0
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      DAEMON_RPC_ADDR: bitcoind:18443
      ORD_HOST: ord
      ORD_PORT: 8090
      ESPLORA_HOST: esplora
      ESPLORA_PORT: 50010
      METASHREW_URI: http://metashrew:8080
      PORT: 18888
    ports:
      - 18888:18888
    restart: unless-stopped
  ord:
    build:
      dockerfile: Dockerfile
      context: ./docker/ord
    image: ord:alkanes
    environment:
      CHAIN: regtest
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      PORT: 8090
      DAEMON_RPC_ADDR: bitcoind:18443
    restart: unless-stopped
  esplora:
    build:
      dockerfile: Dockerfile
      context: ./docker/electrs
    image: esplora:alkanes
    volumes:
      - bitcoin-data:/data/bitcoin
    environment:
      ELECTRS_AUTH: bitcoinrpc:bitcoinrpc
      ELECTRS_NETWORK: regtest
      ELECTRS_DAEMON_RPC_ADDR: bitcoind:18443
      ELECTRS_HTTP_ADDR: 0.0.0.0:50010
      ELECTRS_DB_DIR: /data/electrs
      ELECTRS_DAEMON_DIR: /data/bitcoin
    restart: unless-stopped
