version: "3.3"
volumes:
  bitcoin-data:
  metashrew-data:
  secondary-data:
services:
  bitcoind:
    image: bitcoind:alkanes
    build:
      dockerfile: Dockerfile
      context: ./docker/bitcoind
    volumes:
      - bitcoin-data:/root/.bitcoin
    command:
      ["-txindex", "-regtest=1", "-printtoconsole", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=bitcoinrpc", "-rpcpassword=bitcoinrpc"]
    ports:
      - "18443:18443"
    restart: unless-stopped
  metashrew:
    build:
      dockerfile: Dockerfile
      context: ./docker/metashrew
    image: rockshrew:alkanes
    depends_on:
      - bitcoind
    volumes:
      - metashrew-data:/data
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18443
      AUTH: bitcoinrpc:bitcoinrpc
      DB_PATH: /data
      LOG_FILTERS: none,rockshrew=debug
      HOST: 0.0.0.0
      PORT: 8080
    restart: unless-stopped
  memshrew:
    build:
      dockerfile: Dockerfile
      context: ./docker/memshrew
    image: memshrew:alkanes
    depends_on:
      - bitcoind
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18443
      P2P_ADDR: bitcoind:18444
      AUTH: bitcoinrpc:bitcoinrpc
      LOG_FILTERS: none,memshrew=debug
      HOST: 0.0.0.0
      PORT: 8080
    restart: unless-stopped
  jsonrpc:
    build:
      dockerfile: Dockerfile
      context: ./jsonrpc
    image: jsonrpc:alkanes
    depends_on:
      - bitcoind
      - metashrew
      - ord
      - esplora
    environment:
      HOST: 0.0.0.0
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      DAEMON_RPC_ADDR: bitcoind:18443
      ORD_HOST: ord
      ORD_PORT: 8090
      ESPLORA_HOST: esplora
      ESPLORA_PORT: 50010
      METASHREW_URI: http://metashrew:8080
      PORT: 18888
    ports:
      - 18888:18888
    restart: unless-stopped
  ord:
    build:
      dockerfile: Dockerfile
      context: ./docker/ord
    image: ord:alkanes
    depends_on:
      - bitcoind
    environment:
      CHAIN: regtest
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      PORT: 8090
      DAEMON_RPC_ADDR: bitcoind:18443
    restart: unless-stopped
  esplora:
    build:
      dockerfile: Dockerfile
      context: ./docker/electrs
    image: esplora:alkanes
    depends_on:
      - bitcoind
    volumes:
      - bitcoin-data:/data/bitcoin
    environment:
      ELECTRS_AUTH: bitcoinrpc:bitcoinrpc
      ELECTRS_NETWORK: regtest
      ELECTRS_DAEMON_RPC_ADDR: bitcoind:18443
      ELECTRS_HTTP_ADDR: 0.0.0.0:50010
      ELECTRS_DB_DIR: /data/electrs
      ELECTRS_DAEMON_DIR: /data/bitcoin
    restart: unless-stopped

  espo:
    build:
      dockerfile: Dockerfile
      context: ./docker/espo
    image: espo:alkanes
    depends_on:
      - bitcoind
      - metashrew
      - esplora
    volumes:
      - metashrew-data:/data
      - bitcoin-data:/data/bitcoin
    ports:
      - "9069:9069"
    command:
      [
        "--readonly-metashrew-db-dir", "/data",
        "--port", "9069",
        "--electrum-rpc-url", "http://esplora:50010",
        "--bitcoind-rpc-url", "http://bitcoind:18443",
        "--bitcoind-rpc-user", "bitcoinrpc",
        "--bitcoind-rpc-pass", "bitcoinrpc",
        "--bitcoind-blocks-dir", "/data/bitcoin/regtest/blocks",
        "--espo-db-path", "/db",
        "--tmp-dbs-dir", "/tmp_db"
      ]
    restart: unless-stopped
